# Практическая работа 2

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

### Решение

a) Обе операции неопределены

б) Размерность произведения $A\times B$: $\quad 2\times3$
<br>    BA - неопределена

в) AB - $8\times 8$<br>
BA - $3\times 3$

г) $4\times 4$

---

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

С вашего позволения, я все ж таки решу с numpy, а последнюю уже руками

In [1]:
import numpy as np

In [6]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

AB_sum = A+B
AB = A.dot(B)
BA = B.dot(A)

In [12]:
from IPython.display import Markdown as md

__A + B:__

In [14]:
AB_sum

array([[ 5, -3],
       [ 3,  5]])

_Не могу найти, как красиво напечатать матрицу. Можно, конечно, и самому написать, но неужели в нампай нет такой функции?_

__AB:__

In [17]:
AB

array([[  4, -11],
       [ 12,  -3]])

__BA__

In [19]:
BA

array([[ 1, -8],
       [15,  0]])

---

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

### Решение


In [22]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

### Ответ

In [25]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

---

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [51]:
A = np.array([[4, 1], [5, -2], [2, 3]])


$AA^T$:

In [29]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$A^TA$:

In [31]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

--- 

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [62]:
def A_mult_B(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    sum = 0.
    if A.shape[1] != B.shape[0]:
        print("Wrong size of matrices :(")
        return
    else:
        for i in range(A.shape[0]):
            for j in range (B.shape[1]):
                for k in range(A.shape[1]):
                    sum += A[i][k]*B[k][j]
                C[i][j] = sum
                sum = 0.
    return C

In [57]:
A_mult_B(A, A.T)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [58]:
A_mult_B(A.T, A)

array([[45.,  0.],
       [ 0., 14.]])

In [63]:
A_mult_B(A, A)

Wrong size of matrices :(


# Детерминант

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

$
\sin^2x + \cos^2x = 1
$

_А как программно реализовать проверку для любого x?_

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    

$
4\cdot5\cdot9 + 2\cdot1\cdot0 + 0 - \\
\quad -0  - 0 - 0 = 180
$

In [5]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(a)

180.0

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} \rightarrow
\begin{vmatrix}
1 & 1 & 1\\ 
4 & 1 & 1\\ 
7 & 1 & 1
\end{vmatrix} = 0 $

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(a)

0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   

---
a) $det (A\cdot A) = det(A)\cdot det(A) = 16$

b) $det(A^T) = det(A) = 4 $

c) Если я правильно понимаю, все зависит от размерности А. Ведь если умножить одну строку на 2, то и определитель увеличится вдвое. А здесь мы все строки умножили на 2

---
__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Вторая строка - умноженная на -2 первая => вырождена

In [7]:
a = np.array([[-2, 7, -3], [4, -14, 6], [3, 7, 13]])
np.linalg.det(a)

0.0

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} -> 
\begin{pmatrix}
0 & 1 & 2\\ 
1 & 1 & 1\\ 
1 & 1 & 1
\end{pmatrix} -> 
\begin{pmatrix}
0 & 1 & 2\\ 
0 & 0 & 0\\ 
1 & 1 & 1
\end{pmatrix}
\Rightarrow \text{Ранг 2}$

In [10]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} -> 
\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 2 & 1\\ 
2 & 3 & 5 & 6
\end{pmatrix} \Rightarrow \text{Ранг 3}$

In [11]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3