# Практическая работа 2

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

### Решение

a) Обе операции неопределены

б) Размерность произведения $A\times B$: $\quad 2\times3$
<br>    BA - неопределена

в) AB - $8\times 8$<br>
BA - $3\times 3$

г) $4\times 4$

---

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

С вашего позволения, я все ж таки решу с numpy, а последнюю уже руками

In [1]:
import numpy as np

In [6]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

AB_sum = A+B
AB = A.dot(B)
BA = B.dot(A)

In [12]:
from IPython.display import Markdown as md

__A + B:__

In [14]:
AB_sum

array([[ 5, -3],
       [ 3,  5]])

_Не могу найти, как красиво напечатать матрицу. Можно, конечно, и самому написать, но неужели в нампай нет такой функции?_

__AB:__

In [17]:
AB

array([[  4, -11],
       [ 12,  -3]])

__BA__

In [19]:
BA

array([[ 1, -8],
       [15,  0]])

---

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    

### Решение


In [22]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

### Ответ

In [25]:
3*A - 2*B + 4*C

array([[ 11,  -5],
       [  9, -12]])

---

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [51]:
A = np.array([[4, 1], [5, -2], [2, 3]])


$AA^T$:

In [29]:
A.dot(A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$A^TA$:

In [31]:
A.T.dot(A)

array([[45,  0],
       [ 0, 14]])

--- 

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [62]:
def A_mult_B(A, B):
    C = np.zeros((A.shape[0], B.shape[1]))
    sum = 0.
    if A.shape[1] != B.shape[0]:
        print("Wrong size of matrices :(")
        return
    else:
        for i in range(A.shape[0]):
            for j in range (B.shape[1]):
                for k in range(A.shape[1]):
                    sum += A[i][k]*B[k][j]
                C[i][j] = sum
                sum = 0.
    return C

In [57]:
A_mult_B(A, A.T)

array([[17., 18., 11.],
       [18., 29.,  4.],
       [11.,  4., 13.]])

In [58]:
A_mult_B(A.T, A)

array([[45.,  0.],
       [ 0., 14.]])

In [63]:
A_mult_B(A, A)

Wrong size of matrices :(
