# Собственные значения и вектора

__1.__ Найти собственные векторы и собственные значения линейного оператора

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$



### Решение



$
\begin{vmatrix}
-1 - \lambda & -6\\ 
2 & 6 - \lambda
\end{vmatrix} = 
$

$
= - 6 - 5\lambda + \lambda^2 + 12 =
$

$= \lambda^2 - 5\lambda + 6 \Rightarrow $$\lambda = 3; 2$

---
$A\cdot v_1 = 3\cdot v_1$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} 
\cdot
\begin{pmatrix}
v_x\\
v_y
\end{pmatrix} =
\begin{pmatrix}
3v_x\\
3v_y
\end{pmatrix}
$

$
\begin{pmatrix}
-v_x - 6v_y\\
2v_x + 6v_y
\end{pmatrix} = 
\begin{pmatrix}
3v_x\\
3v_y
\end{pmatrix}
$


$
\begin{cases}
-4v_x - 6v_y = 0\\
2v_x + 3v_y = 0
\end{cases}
$


$
\begin{cases}
v_x = -\frac{3}{2}v_y\\
v_y = 1
\end{cases}
$


---
$A\cdot v_1 = 2\cdot v_1$

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix} 
\cdot
\begin{pmatrix}
v_x\\
v_y
\end{pmatrix} =
\begin{pmatrix}
2v_x\\
2v_y
\end{pmatrix}
$

$
\begin{pmatrix}
-v_x - 6v_y\\
2v_x + 6v_y
\end{pmatrix} = 
\begin{pmatrix}
2v_x\\
2v_y
\end{pmatrix}
$


$
\begin{cases}
-3v_x - 6v_y = 0\\
2v_x + 4v_y = 0
\end{cases}
$


$
\begin{cases}
v_x = -\frac{1}{2}v_y\\
v_y = 1
\end{cases}
$





In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [9]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
print(w), print(v)



[2. 3.]
[[-0.89  0.83]
 [ 0.45 -0.55]]


(None, None)

In [8]:
np.array([-3./2, 1]) / np.linalg.norm(np.array([-3./2, 1]))

array([-0.83,  0.55])

In [10]:
np.array([-1./2, 1]) / np.linalg.norm(np.array([-1./2, 1]))

array([-0.45,  0.89])

--- 
---
__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Показать, что __любой__ вектор является для него собственным.

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} 
\cdot
\begin{pmatrix}
v_x\\
v_y
\end{pmatrix} =
\begin{pmatrix}
\lambda\cdot v_x\\
\lambda\cdot v_y
\end{pmatrix}
$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix} 
\cdot
\begin{pmatrix}
v_x\\
v_y
\end{pmatrix} =
\begin{pmatrix}
- v_x\\
- v_y
\end{pmatrix}
$

---
__3.__ Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix} 
\cdot
\begin{pmatrix}
1\\
1
\end{pmatrix} =
\begin{pmatrix}
\lambda\\
\lambda
\end{pmatrix}
$

$\begin{pmatrix}
2\\ 
2
\end{pmatrix} 
 =
\begin{pmatrix}
\lambda\\
\lambda
\end{pmatrix}
$

__Да__, это собственный вектор, соответствующий собственному значению 2

--- 
**4.** Пусть линейный оператор задан матрицей

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0&3
\end{pmatrix} 
\cdot
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix} =
\begin{pmatrix}
3\lambda\\
-3\lambda\\
-4\lambda
\end{pmatrix}
$

$\begin{pmatrix}
-9\\ 
9\\
-12
\end{pmatrix} 
 =
\begin{pmatrix}
3\lambda\\
-3\lambda\\
-4\lambda
\end{pmatrix}
$

__Не является__