# Системы линейных уравнений

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

### Решение



$
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1&-2 \\
2&1&-1&1\\
1&1&-3&1 
\end{matrix}\right|
\begin{matrix}
0\\
-1\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1&-2 \\
1&0&0&3\\
0&0&-2&3 
\end{matrix}\right|
\begin{matrix}
0\\
-1\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
$ 

$\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1&-2 \\
1&0&0&3\\
0&0&-2&0 
\end{matrix}\right|
\begin{matrix}
0\\
-1\\
5
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&1&-1&0 \\
1&0&0&1\\
0&0&1&0 
\end{matrix}\right|
\begin{matrix}
-\frac{2}{3}\\
-\frac{1}{3}\\
-\frac{5}{2}
\end{matrix}
\end{pmatrix}
\rightarrow$ 

$\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
0&1&0&-1 \\
1&0&0&1\\
0&0&1&0 
\end{matrix}\right|
\begin{matrix}
-\frac{1}{3}-\frac{5}{2}\\
-\frac{1}{3}\\
-\frac{5}{2}
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&0&0&1\\
0&1&0&-1 \\
0&0&1&0 
\end{matrix}\right|
\begin{matrix}
-\frac{1}{3}\\
-\frac{1}{3}-\frac{5}{2}\\
-\frac{5}{2}
\end{matrix}
\end{pmatrix}
$ 

$x_3 = -\frac{5}{2}\\
x_4 = C\\
x_2  = -\frac{17}{6} + C\\
x_1  = -\frac{1}{3} - C
$

$
(x_1, x_2, x_3, x_4) = (-\frac{1}{3}, -\frac{17}{6}, -\frac{5}{2}) + C\cdot(-1, 1, 0, 1)
$

---
__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$


### Решение



$
\begin{pmatrix}
\left.\begin{matrix}
3&-1&1 \\
2&-5&-3\\
1&1&-1
\end{matrix}\right|
\begin{matrix}
4\\
-17\\
0
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
4&0&0 \\
0&-7&-1\\
1&1&-1
\end{matrix}\right|
\begin{matrix}
4\\
-17\\
0
\end{matrix}
\end{pmatrix}
\rightarrow
$ 

$
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&0&0 \\
0&-7&-1\\
0&1&-1
\end{matrix}\right|
\begin{matrix}
1\\
-17\\
-1
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&0&0 \\
0&-8&0\\
0&1&-1
\end{matrix}\right|
\begin{matrix}
1\\
-16\\
-1
\end{matrix}
\end{pmatrix}
\rightarrow
$ 

$
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&0&0 \\
0&1&0\\
0&1&-1
\end{matrix}\right|
\begin{matrix}
1\\
2\\
-1
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1&0&0 \\
0&1&0\\
0&0&1
\end{matrix}\right|
\begin{matrix}
1\\
2\\
3
\end{matrix}
\end{pmatrix}
\rightarrow
$ 

$
x_3 = 3\\
x_2 = 2\\
x_1 = 1
$

__Совместна и определена__

Проверим

In [5]:
import numpy as np

In [4]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
np.linalg.det(a)

32.0

Матрица к-тов невырождена, число неизвестных = числу строк. Все верно.

б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$

$
\begin{pmatrix}
\left.\begin{matrix}
2&-4&6 \\
1&-2&3\\
3&-6&9
\end{matrix}\right|
\begin{matrix}
1\\
-2\\
5
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
0&0&0 \\
0&-7&-1\\
0&0&0
\end{matrix}\right|
\begin{matrix}
5\\
-2\\
2
\end{matrix}
\end{pmatrix}
\rightarrow
$ 

__Несовместна__

 в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

$
\begin{pmatrix}
\left.\begin{matrix}
1&2&5 \\
3&1&-8
\end{matrix}\right|
\begin{matrix}
4\\
-2
\end{matrix}
\end{pmatrix}
$ 

Коэффициенты независимы линейно, __система совместна, но не определена__

---
__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$



$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}$

Число переменных = числу строк. Система коэффициентов невырождена. Все __соместно, и все определено__.

---
__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}
$

Ну, мы это уже считали - определитель $\ne0$. Система совместна всегда. И определена тоже всегда

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(a)

0.0

О нет. Как так. Сейчас разберемся. а пока видим, что система либо неопределена, либо несовместна

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
3 & 3 & 3
\end{matrix}\right|
\begin{matrix}
a\\ 
b - a\\
c - b
\end{matrix}
\end{pmatrix}
\rightarrow$

$
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c - 2b + a
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
\frac{4a - b}{3}\\
c - 2b + a
\end{matrix}
\end{pmatrix}$

__Если c - 2b + a = 0, то система несовместна__

В сотальных случаях совместна, но неопределена

# Решение систем линейных уравнений

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    

$
\Delta = 
\begin{vmatrix}
1&-2\\
3&-4
\end{vmatrix} = -4 + 6 = 2
$

$
\Delta_1 = 
\begin{vmatrix}
1&-2\\
7&-4
\end{vmatrix} = -4 + 14 = 10
$

$
\Delta_2 = 
\begin{vmatrix}
1&1\\
3&7
\end{vmatrix} = 7 - 3 = 4
$

$x_1 = 5, x_2 = 2$

In [9]:
a = np.array([[1, -2], [3, -4]])
b = np.array([1, 7]).T
np.linalg.solve(a, b)

array([5., 2.])

   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$
\Delta = 
\begin{vmatrix}
2&-1&5\\
1&1&-3\\
2&4&1
\end{vmatrix} = 2 + 6 + 20 -10+24+1
$

In [10]:
2 + 6 + 20 -10+24+1

43

$
\Delta_1 = 
\begin{vmatrix}
10&-1&5\\
-2&1&-3\\
1&4&1
\end{vmatrix} = 10 + 3 -40 - 5 + 120 - 2 
$

In [11]:
10 + 3 -40 - 5 + 120 - 2 

86

$
\Delta_2 = 
\begin{vmatrix}
2&10&5\\
1&-2&-3\\
2&1&1
\end{vmatrix} = -4 - 60 + 5 + 20 + 6 - 10
$

In [12]:
-4 - 60 + 5 + 20 + 6 - 10

-43

$
\Delta_3 = 
\begin{vmatrix}
2&-1&10\\
1&1&-2\\
2&4&1
\end{vmatrix} = 2 + 4 + 40 - 20 + 16 + 1
$

In [13]:
2 + 4 + 40 - 20 + 16 + 1

43

__Ответ__

$(x_1, x_2, x_3) = (2, -1, 1) $

Проверим:

In [14]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

np.linalg.solve(a, b)

array([ 2., -1.,  1.])

---
__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    

$
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0 \\
0&1&0\\
0&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&2&4 \\
2&9&12\\
3&26&30
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0 \\
2&1&0\\
3&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&2&4 \\
0&5&4\\
0&20&18
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0 \\
2&1&0\\
3&4&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&2&4 \\
0&5&4\\
0&0&2
\end{matrix}
}_U
\end{pmatrix}
$ 

   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    

$
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0&0 \\
0&1&0&0\\
0&0&1&0\\
0&0&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&1&2&4 \\
2&5&8&9\\
3&18&29&18\\
4&22&53&33
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0&0 \\
2&1&0&0\\
3&0&1&0\\
4&0&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&1&2&4 \\
0&3&4&1\\
0&15&23&6\\
0&18&45&17
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
$ 

$
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0&0 \\
2&1&0&0\\
3&5&1&0\\
4&6&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&1&2&4 \\
0&3&4&1\\
0&0&3&1\\
0&0&21&11
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0&0 \\
2&1&0&0\\
3&5&1&0\\
4&6&7&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
1&1&2&4 \\
0&3&4&1\\
0&0&3&1\\
0&0&0&4
\end{matrix}
}_U
\end{pmatrix}
$ 

Давайте проверим, если не возражаете

In [7]:
a = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])
l= np.array([[1,  0, 0, 0], [2, 1, 0, 0], [3, 5, 1, 0], [4, 6, 7, 1]])
u = np.array([[1, 1, 2, 4], [0, 3, 4, 1], [0, 0, 3, 1], [0,0,0,4]])


In [10]:
a - l.dot(u)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

Кайф

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0 \\
0&1&0\\
0&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
2&1&3\\
11&7&5\\
9&8&4
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0 \\
\frac{11}{2}&1&0\\
\frac{9}{2}&0&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
2&1&3\\
0&\frac{3}{2}&-\frac{23}{2}\\
0&\frac{7}{2}&-\frac{19}{2}
\end{matrix}
}_U
\end{pmatrix}
\rightarrow
$ 

$
\rightarrow
\begin{pmatrix}
\left.
\underbrace
{\begin{matrix}
1&0&0 \\
\frac{11}{2}&1&0\\
\frac{9}{2}&\frac{7}{3}&1
\end{matrix}
}_L
\right|
\underbrace{
\begin{matrix}
2&1&3\\
0&\frac{3}{2}&-\frac{23}{2}\\
0&0&\frac{52}{3}
\end{matrix}
}_U
\end{pmatrix}
$ 

In [24]:
-19./2 + 23./2*7./3

17.333333333333332

In [25]:
l = np.array( [[1, 0, 0], [11./2, 1, 0], [9./2, 7./3, 1]] )
u = np.array( [[2, 1, 3], [0, 3./2, -23./2], [0, 0, 52./3]] )
a = np.array( [[2, 1, 3], [11, 7, 5], [9, 8, 4]] )

a - l.dot(u)

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 3.55271368e-15]])

Подскажите, пожалуйста, как делать LU разложение по-питоновски? У scipy linalg есть функция lu, но там еще матрица перестановок

$L\cdot y = (1, -6, -5)^T$

$\begin{pmatrix}
1&0&0 \\
\frac{11}{2}&1&0\\
\frac{9}{2}&\frac{7}{3}&1
\end{pmatrix}
\cdot
\begin{pmatrix}
y_1\\
y_2\\
y_3
\end{pmatrix}
= 
\begin{pmatrix}
1\\
-6\\
-5
\end{pmatrix}
$

$
\begin{cases}
y_1 = 1\\
\frac{11}{2} + y_2 = -6\\
\frac{9}{2} + \frac{7}{3} y_2 + y_3 = -5
\end{cases}
$

$
\begin{cases}
y_1 = 1\\
y_2 = -\frac{23}{2}\\
\frac{9}{2} - \frac{7}{3} \cdot \frac{23}{2} + y_3 = -5
\end{cases}
$

$
\begin{cases}
y_1 = 1\\
y_2 = -\frac{23}{2}\\
y_3 = \frac{52}{3}
\end{cases}
$

In [37]:
a = np.array( [[1, 0, 0], [11./2, 1, 0], [9./2, 7./3, 1]] )
y = np.array( [1, -23./2, 52./3])
b = np.array( [1, -6, -5])
a.dot(y) - b

array([ 0.00000000e+00,  0.00000000e+00, -3.55271368e-15])

$U\cdot x = (1, -\frac{23}{2}, \frac{52}{3})^T$

$
\begin{pmatrix}
2&1&3\\
0&\frac{3}{2}&-\frac{23}{2}\\
0&0&\frac{52}{3}
\end{pmatrix}
\cdot
\begin{pmatrix}
x_1\\
x_2\\
x_3
\end{pmatrix} =
\begin{pmatrix}
1\\
-\frac{23}{2}\\
\frac{52}{3}
\end{pmatrix}
$

$
\begin{cases}
x_3 = 1\\
x_2 = 0\\
x_1 = -1
\end{cases}
$

Давайте проверим, если не возражаете

In [38]:
a = np.array( [[2, 1, 3], [11, 7, 5], [9, 8, 4]] )
b = np.array([1, -6, -5]).T
x = np.array([-1, 0, 1]).T

In [39]:
a.dot(x) - b

array([0, 0, 0])

Все ок

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$


$$l_{11}=\sqrt{a_{11}}=\sqrt{81} = 9,$$
$$l_{21}=\frac{a_{21}}{l_{11}}=\frac{-45}{9} = -5,$$
$$l_{31}=\frac{a_{31}}{l_{11}}=\frac{45}{9} = 5,$$

$$l_{22}=\sqrt{a_{22}-l_{21}^{2}}=\sqrt{50 - 25}=5,$$
$$l_{32}=\frac{1}{l_{22}}\left ( a_{32}-l_{21}l_{31} \right)=\frac{1}{5}\left ( -15 +25 \right )=2,$$

$$l_{33}=\sqrt{a_{33}-l_{31}^{2}-l_{32}^{2}}=\sqrt{38 - 25 -4} = 3$$


$$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}, 
\; \; 
L^{T} = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}.$$

Решим систему $Ly=b:$

$$\begin{cases}
9y_{1}=531, \\
-5y_{1}+5y_{2}=-460, \\
5y_{1}+2y_{2}+3y_{3}=193.
\end{cases}$$

$$\begin{cases}
y_{1}=59, \\
-5\cdot 59+5y_{2}=-460, \\
5\cdot 59+2y_{2}+3y_{3}=193.
\end{cases}$$

$$\begin{cases}
y_{1}=59, \\
y_{2}=-33, \\
y_{3}=11.
\end{cases}$$

In [43]:
5*59 - 2*33-193
_/(-3)

-3.6666666666666665

Решим систему $L^T x=y:$

$$\begin{cases}
9x_{1} - 5x_{2} + 5x_{3} =59, \\
5x_{2}+2x_{3}=-33, \\
3x_{3}=11.
\end{cases}$$

$$\begin{cases}
x_{1}=\frac{1}{3}, \\
x_{2}=\frac{121}{15}, \\
x_{3}=\frac{11}{3}.
\end{cases}$$

### Ответ

$(\frac{1}{3}, -\frac{121}{3}, \frac{11}{3})$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

Попробую сделать реализацию Гаусса - это на мой взгляд, сложнее будет закодить, зато более универсальный

In [113]:
A = np.array([[1, 1, -1, -2], [2, 1, -1, 1], [1,  1, -3, 1]])
b = np.array([0,-2, 4]).T

In [83]:
A.shape

(3, 4)

In [226]:
# Напишем функцию для транспозиции 2х строк матрицы
eps = 1e-5
def swap_ij(A, i, j):
    tmp = []
    tmp = A[j].copy()
    A[j] = A[i]    
    A[i] = tmp
    return A

def string_transformation(A, i, j, alpha):
    A[j] = A[j] + alpha*A[i]
    return A

# Прямой ход - приведение к диагональному виду
def my_Gauss1(A):
    n, m = A.shape
    for j in range(0, min(n, m-1)): # Последний столбец - свободных членов
        print(f'Step {j}:')
        # Находим ненулевой элемент в столбце
        for i in range(j,n):
            #  Если ноль, то пропускаем, идем дальше по столбцу
            #  Иначе, swap and break
            if (A[i, j] - 0. < eps):
                continue
            else:
                swap_ij(A, i, j)
                break
        print(A)
        # Занулим все элементы ниже
        for i in range(j+1, n):
            print(f'alpha: {-A[i, j]/A[j, j]}')
            string_transformation(A, j, i, -A[i, j]/A[j, j])
            print(A)
            
    return A

# Обратный ход
# Чет совсем туплю, давайте сделаю пока хотя бы для квадратной матрицы
def my_Gauss2(A):
    print('Обратный ход')

    step = 0
    n,m = A.shape
    x = np.empty(m-1)
    for i in range(n-1, -1, -1):
#        step+=1
        print(A)
        if A[i, i] == 0:
            if A[i, m-1] != 0:
                print("Система несовместна")
                return 0
            else:
                x[i] = 'C_'+str(i)
        else:
            x[i] = A[i, m-1]/A[i,i]
            for k in range(i-1, -1, -1):
                print('ok')
                string_transformation(A, i, k, -A[k, i]/A[i,i])
                print(A)
    return x
        
def my_Gauss(A, b):
    x = []
    A_exp = np.append(A, b.reshape((b.shape[0], 1)), axis = 1)
    my_Gauss1(A_exp)
    x = my_Gauss2(A_exp)
    return x 
            
            

In [227]:
A = np.array([[2., -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1]).reshape((3, 1))
print(b.shape)
np.append(A, b, axis = 1)


(3, 1)


array([[ 2., -1.,  5., 10.],
       [ 1.,  1., -3., -2.],
       [ 2.,  4.,  1.,  1.]])

In [228]:
my_Gauss(A, b)

Step 0:
[[ 2. -1.  5. 10.]
 [ 1.  1. -3. -2.]
 [ 2.  4.  1.  1.]]
alpha: -0.5
[[ 2.  -1.   5.  10. ]
 [ 0.   1.5 -5.5 -7. ]
 [ 2.   4.   1.   1. ]]
alpha: -1.0
[[ 2.  -1.   5.  10. ]
 [ 0.   1.5 -5.5 -7. ]
 [ 0.   5.  -4.  -9. ]]
Step 1:
[[ 2.  -1.   5.  10. ]
 [ 0.   1.5 -5.5 -7. ]
 [ 0.   5.  -4.  -9. ]]
alpha: -3.3333333333333335
[[ 2.         -1.          5.         10.        ]
 [ 0.          1.5        -5.5        -7.        ]
 [ 0.          0.         14.33333333 14.33333333]]
Step 2:
[[ 2.         -1.          5.         10.        ]
 [ 0.          1.5        -5.5        -7.        ]
 [ 0.          0.         14.33333333 14.33333333]]
Обратный ход
[[ 2.         -1.          5.         10.        ]
 [ 0.          1.5        -5.5        -7.        ]
 [ 0.          0.         14.33333333 14.33333333]]
ok
[[ 2.         -1.          5.         10.        ]
 [ 0.          1.5         0.         -1.5       ]
 [ 0.          0.         14.33333333 14.33333333]]
ok
[[ 2.         -1.     

array([ 2., -1.,  1.])

Удивительно: похоже, это работает

Тут следует упомянуть, что я конкретно схалтурил в следующих вещах: 
1) Алгоритм работает только для квадратных матриц
2) В случае неопределенной системы алгоритм не сработает - он не завершен. Но так как я уже все сроки напрочь просрочил, всему свое время (то есть, задвинем пока). Но если вы будете настаивать на завершении алгоритма, я пойму