# Сингулярное разложение матриц

1. Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

2. Для матрицы из предыдущего задания найти:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1., 2., 0],
              [0,0,5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1.  2.  0.]
 [ 0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


In [3]:
U, s, W = np.linalg.svd(A)

# Транспонируем матрицу W
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [4]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


Let's check

In [5]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


Fine

### 2) Найдем нормы

Евклидова - просто максимальный диагональй элемент D

In [6]:
Euclid_norm = s[0]
Euclid_norm

8.824868854820444

Фробениус

In [8]:
Frobenius_norm = (s**2).sum()
Frobenius_norm

122.00000000000003

In [10]:
8.82**2 + 6.14**2 + 2.53**2

121.89289999999998

Отличие в значениях, полагаю, из-за 3-го знака после запятой

Если так, то...все)
Буду ждать от вас комментария, а пока спасибо большое за курс, было интересно и познавательно! Надеюсь, если будут появляться какие смежные вопросы из мира DS, могу обращаться?)